# XOR

- 하나의 히든 레이어를 도입한다.
- input layer는 2개의 노드 + 1개의 바이어스
- hidden layer는 3개의 노드 + 1개의 바이어스
- output은 하나의 노드로 한다.

In [15]:
X = [[0,0,1],[1,0,1],[0,1,1],[1,1,1]] # 세번째 항은 bias
y = [0,1,1,0]

위의 데이터를 neural networks에서 backpropagation을 이용하여으로 학습시켜라.

In [16]:
import numpy as np
import matplotlib.pyplot as plt

In [17]:
def f(x):
    return 1/(1+np.exp(-x))

In [18]:
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = np.array([[0],[1],[1],[0]])

In [19]:
inputs, hiddens, outputs = 3, 4, 1

In [20]:
np.random.seed(1)
w = 2*np.random.random((inputs, hiddens))-1
omega = 2*np.random.random((hiddens, outputs))-1
w

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [21]:
dh=[0,0,0,0]
eta=1
for n in range(100):
    E=0
    for i in range(4):
        neth = np.dot(X[i],w)
        h=f(neth)
        neto=np.dot(h,omega)
        o=f(neto)
        
        E = E + (o-y[i])**2
        do = (o-y[i])*f(neto)*(1-f(neto))
        for j in range(4):
            dh[j]=do*omega[j]*f(neth[j])*(1-f(neth[j]))
            omega[j]=omega[j]-eta*do*h[j]
            for k in range(3):
                w[k][j]=w[k][j]-eta*dh[j]*X[i][k]

E



array([0.87872817])

In [22]:
w,o

(array([[-0.60005256,  0.39826775, -2.16685439, -0.62644669],
        [-1.07249971, -1.47032335, -2.25017423, -0.57141318],
        [-0.56199459, -0.45898948, -0.15969674,  0.17780685]]),
 array([0.565041]))